from=./armorer.png
to=optigui:gui/villagers/armorer.png
w=18
h=23
x=114
y=37
duration.0=300
duration.1=2
duration.2=4
duration.3=2
duration.4=80
duration.5=40
duration.6=2
duration.7=60
duration.8=60
duration.9=40
duration.10=60
duration.11=60
duration.12=80
duration.13=60
duration.14=2
duration.15=2
duration.16=2