from=./ender_eye.png
to=optigui:gui/chests/ender_chest.png
w=10
h=10
x=155
y=6
duration.0=200
duration.1=2
duration.2=2
duration.3=10
duration.4=2
duration.5=2
duration.6=60
duration.7=3
duration.8=30
duration.9=3
duration.10=3
duration.11=3
duration.12=60
duration.13=30
duration.14=2
duration.15=60
duration.16=60
duration.17=3
duration.18=3